services:
  - type: web
    name: cumulative-assessment-node-express-and-postgresql
    runtime: node
    region: virginia
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PRODUCTION_DATABASE_URL
    preDeployCommand: |
      npx knex migrate:latest --knexfile knexfile.js
      npx knex seed:run --knexfile knexfile.js
